### PR TITLE
removing refs to nil obj in post job, better tests for post job

### PR DESCRIPTION
**Pull request by jenlindner**

### CODE REVIEW

**Comment by csyversen** [comment]
yassssss

**Comment by jenlindner** [comment]
lol

**Comment by jenlindner** [comment]
Just think how happy you'd be if I deleted some stale branches

**Comment by csyversen** [comment]
do eeeeet

**Comment by csyversen** [comment]
looks good! lets test it

**Comment by jenlindner** [comment]
thanks!

**Pull request merged**
